Initial action workflow for github.

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -25,11 +25,46 @@ jobs:
         uses: actions/cache@v4.2.0
         with:
           path: oracle-tools
-          key: oracle-tools
+          key: oracle-tools-23.6
       - name: Download Oracle Tools
-        if: steps.cache-primes.outputs.cache-hit != 'true'
+        if: steps.cache-oracle-tools.outputs.cache-hit != 'true'
         run: |
-          echo "Hello" > /oracle-tools/hello.txt
-          echo "I ran."
-      - name: Test download
-        run: cat /oracle-tools/hello.txt
+          mkdir -p oracle-tools/instantclient
+          cd oracle-tools
+          wget https://download.oracle.com/otn_software/linux/instantclient/2360000/instantclient-basic-linux.x64-23.6.0.24.10.zip
+          wget https://download.oracle.com/otn_software/linux/instantclient/2360000/instantclient-sqlplus-linux.x64-23.6.0.24.10.zip
+          wget https://download.oracle.com/otn_software/linux/instantclient/2360000/instantclient-tools-linux.x64-23.6.0.24.10.zip
+          unzip -o instantclient-basic*.zip
+          unzip -o instantclient-sqlplus*.zip
+          unzip -o instantclient-tools*.zip
+          rm -f *.zip
+          mv instantclient_*/* ./instantclient
+          ls -l instantclient/
+          wget https://github.com/utPLSQL/utPLSQL-cli/releases/download/3.1.9/utPLSQL-cli.zip
+          unzip utPLSQL-cli.zip
+          rm utPLSQL-cli.zip
+          # if the ojdbc version in utPLSQL-cli doesn't match the instant client
+          rm utPLSQL-cli/lib/*-19.3.0.0.jar
+          cp instantclient/ojdbc8.jar utPLSQL-cli/lib
+          cp instantclient/ucp.jar utPLSQL-cli/lib
+      - name: Set Oracle Home
+        run: |
+          cd oracle-tools
+          echo "LD_LIBRARY_PATH=`pwd`/instantclient" >> $GITHUB_ENV
+          echo "ORACLE_HOME=`pwd`/instantclient" >> $GITHUB_ENV
+          echo "PATH=`pwd`/instantclient:`pwd`/utPLSQL-cli/bin:$PATH" >> $GITHUB_ENV
+      - name: Prep Database
+        working-directory: schema
+        run: ant docker.prepdb -Doracle.image=gvenzl/oracle-free:23.4-full-faststart
+      - name: Install Schema
+        working-directory: schema
+        run: ant docker.install -Doracle.image=gvenzl/oracle-free:23.4-full-faststart
+      - name: Run Tests
+        working-directory: schema
+        run: ant  test -Dbuilduser.overrides=build/overrides.external.xml -Doracle.image=gvenzl/oracle-free:23.4-full-faststart
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          annotation_only: true
+          report_paths: '**/build/test-results/test/TEST-*.xml'
